"""MmrRegFileCHeaderEmitter — C header generator for MMR RegisterFile classes.

Emits a self-contained C header with:

- Register offset ``#define``\\ s (``PREFIX_REGNAME_OFFSET``)
- Per-field shift and mask ``#define``\\ s (``PREFIX_REGNAME_FIELDNAME_SHIFT/MASK``)
- Generic MMIO access macros (``PREFIX_RD``, ``PREFIX_WR``)
- Per-field read/write/clear macros filtered by SW access policy

Standalone usage::

    from zuspec.be.sw.mmr.c_header import emit_c_header
    h_text = emit_c_header(MyRegs)
"""
from __future__ import annotations

import re
from typing import List, Optional


def _upper(name: str) -> str:
    """CamelCase / mixed → UPPER_SNAKE."""
    s = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', name)
    s = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s)
    return s.upper()


def _ones_mask(width: int) -> str:
    """Hex mask string for *width* consecutive ones, e.g. ``0x3U``."""
    return f"0x{(1 << width) - 1:X}U"


class MmrRegFileCHeaderEmitter:
    """Emits a C header for a ``RegisterFile`` subclass.

    Parameters
    ----------
    regfile_cls:
        A ``@zdc.regfile``-decorated ``RegisterFile`` subclass.
    prefix:
        Macro prefix (default: UPPER_SNAKE of the class name).
    data_type:
        C type used for register values (default ``uint32_t``).
    include_stdint:
        If True, emit ``#include <stdint.h>`` (default True).
    """

    def __init__(
        self,
        regfile_cls,
        prefix:        Optional[str] = None,
        data_type:     str = "uint32_t",
        include_stdint: bool = True,
    ):
        self._cls        = regfile_cls
        self._prefix     = prefix or _upper(regfile_cls.__name__)
        self._data_type  = data_type
        self._inc_stdint = include_stdint
        self._regs       = getattr(regfile_cls, '_mmr_reg_classes', [])

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def emit(self) -> str:
        """Return the complete C header as a string."""
        lines: List[str] = []
        lines += self._emit_header_guard_open()
        if self._inc_stdint:
            lines += ["#include <stdint.h>", ""]
        lines += self._emit_offsets()
        lines += self._emit_field_defines()
        lines += self._emit_access_macros()
        lines += self._emit_field_macros()
        lines += self._emit_header_guard_close()
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Include guard
    # ------------------------------------------------------------------

    def _guard_name(self) -> str:
        return f"{self._prefix}_H"

    def _emit_header_guard_open(self) -> List[str]:
        g = self._guard_name()
        return [
            f"/* Auto-generated by zuspec MmrRegFileCHeaderEmitter */",
            f"/* Source: {self._cls.__name__} */",
            f"#ifndef {g}",
            f"#define {g}",
            "",
        ]

    def _emit_header_guard_close(self) -> List[str]:
        return ["", f"#endif /* {self._guard_name()} */", ""]

    # ------------------------------------------------------------------
    # Register offsets
    # ------------------------------------------------------------------

    def _emit_offsets(self) -> List[str]:
        lines = ["/* Register offsets */"]
        for reg_name, reg_cls in self._regs:
            off  = reg_cls._mmr_offset
            macro = f"{self._prefix}_{_upper(reg_name)}_OFFSET"
            lines.append(f"#define {macro:<52} 0x{off:02X}U")
        lines.append("")
        return lines

    # ------------------------------------------------------------------
    # Field shift / mask defines
    # ------------------------------------------------------------------

    def _emit_field_defines(self) -> List[str]:
        from zuspec.dataclasses.mmr.enums import SW
        lines = []
        for reg_name, reg_cls in self._regs:
            fields = getattr(reg_cls, '_mmr_fields', [])
            if not fields:
                continue
            lines.append(f"/* {reg_name} fields */")
            for fname, fd in fields:
                p    = f"{self._prefix}_{_upper(reg_name)}_{_upper(fname)}"
                lsb  = fd.lsb
                w    = fd._width
                mask = f"({_ones_mask(w)} << {p}_SHIFT)"
                lines.append(f"#define {p + '_SHIFT':<52} {lsb}U")
                lines.append(f"#define {p + '_MASK':<52} {mask}")
            lines.append("")
        return lines

    # ------------------------------------------------------------------
    # Generic MMIO access macros
    # ------------------------------------------------------------------

    def _emit_access_macros(self) -> List[str]:
        p  = self._prefix
        dt = self._data_type
        return [
            "/* Generic MMIO access */",
            f"#define {p}_RD(base, off)        (*(volatile {dt} *)((uintptr_t)(base) + (off)))",
            f"#define {p}_WR(base, off, val)   (*(volatile {dt} *)((uintptr_t)(base) + (off)) = ({dt})(val))",
            f"#define {p}_RMW(base, off, mask, shift, val) \\",
            f"    {p}_WR((base), (off), ({p}_RD((base), (off)) & ~(mask)) | \\",
            f"        ((({dt})(val) << (shift)) & (mask)))",
            "",
        ]

    # ------------------------------------------------------------------
    # Per-field read / write / clear macros
    # ------------------------------------------------------------------

    def _emit_field_macros(self) -> List[str]:
        from zuspec.dataclasses.mmr.enums import SW
        lines = ["/* Field access macros */"]
        for reg_name, reg_cls in self._regs:
            off_macro = f"{self._prefix}_{_upper(reg_name)}_OFFSET"
            for fname, fd in getattr(reg_cls, '_mmr_fields', []):
                p = f"{self._prefix}_{_upper(reg_name)}_{_upper(fname)}"
                sw = fd.sw

                # Read macro (all SW-readable fields)
                if sw not in (SW.WO, SW.NA):
                    lines.append(
                        f"#define {p + '_RD(base)':<52} \\"
                    )
                    lines.append(
                        f"    (({self._data_type})("
                        f"{self._prefix}_RD((base), {off_macro}) "
                        f"& {p}_MASK) >> {p}_SHIFT)"
                    )

                # Write macro (SW-writable fields)
                if sw not in (SW.RO, SW.NA):
                    # woclr: write-1-to-clear — emit a _CLR macro instead of _WR
                    if fd.onwrite == 'woclr':
                        lines.append(
                            f"#define {p + '_CLR(base)':<52} \\"
                        )
                        lines.append(
                            f"    {self._prefix}_WR((base), {off_macro}, "
                            f"{p}_MASK)"
                        )
                    else:
                        lines.append(
                            f"#define {p + '_WR(base, val)':<52} \\"
                        )
                        lines.append(
                            f"    {self._prefix}_RMW((base), {off_macro}, "
                            f"{p}_MASK, {p}_SHIFT, (val))"
                        )
        lines.append("")
        return lines


# ---------------------------------------------------------------------------
# Standalone entry point
# ---------------------------------------------------------------------------

def emit_c_header(
    regfile_cls,
    prefix:        Optional[str] = None,
    data_type:     str = "uint32_t",
    include_stdint: bool = True,
) -> str:
    """Generate a C header for a ``RegisterFile`` subclass.

    Parameters
    ----------
    regfile_cls:
        A ``@zdc.regfile``-decorated ``RegisterFile`` subclass.
    prefix:
        Macro prefix (default: UPPER_SNAKE of the class name).
    data_type:
        C type for register values (default ``uint32_t``).
    include_stdint:
        If True, emit ``#include <stdint.h>`` (default True).

    Returns
    -------
    str
        The complete C header text.
    """
    return MmrRegFileCHeaderEmitter(
        regfile_cls,
        prefix=prefix,
        data_type=data_type,
        include_stdint=include_stdint,
    ).emit()
