"""MmrRegFilePyDriverEmitter — Python driver generator for MMR RegisterFile classes.

Emits a self-contained Python class that wraps a user-supplied MMIO
``read``/``write`` callable pair, providing typed, field-level access
to every register in the ``RegisterFile``.

The API mirrors the ``zdc`` simulation API:

- ``read_<REG>()``, ``write_<REG>(value)`` — raw 32-bit register access
- ``get_<REG>_<FIELD>()`` — read a single field (SW-readable only)
- ``set_<REG>_<FIELD>(value)`` — RMW-write a single field (SW-writable only)
- ``clr_<REG>_<FIELD>()`` — write-1-to-clear for ``onwrite='woclr'`` fields

Standalone usage::

    from zuspec.be.sw.mmr.py_driver import emit_py_driver
    src = emit_py_driver(MyRegs)
"""
from __future__ import annotations

import re
import textwrap
from typing import List, Optional


def _snake(name: str) -> str:
    """CamelCase / mixed → lower_snake."""
    s = re.sub(r'([A-Z]+)([A-Z][a-z])', r'\1_\2', name)
    s = re.sub(r'([a-z0-9])([A-Z])', r'\1_\2', s)
    return s.lower()


class MmrRegFilePyDriverEmitter:
    """Emits a Python driver class for a ``RegisterFile`` subclass.

    Parameters
    ----------
    regfile_cls:
        A ``@zdc.regfile``-decorated ``RegisterFile`` subclass.
    class_name:
        Name for the generated class (default: ``<ClassName>Driver``).
    """

    def __init__(self, regfile_cls, class_name: Optional[str] = None):
        self._cls        = regfile_cls
        self._class_name = class_name or (regfile_cls.__name__ + "Driver")
        self._regs       = getattr(regfile_cls, '_mmr_reg_classes', [])

    # ------------------------------------------------------------------
    # Public entry point
    # ------------------------------------------------------------------

    def emit(self) -> str:
        """Return the complete Python driver source as a string."""
        lines: List[str] = []
        lines += self._emit_module_header()
        lines += self._emit_class_body()
        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Module header
    # ------------------------------------------------------------------

    def _emit_module_header(self) -> List[str]:
        return [
            "# Auto-generated by zuspec MmrRegFilePyDriverEmitter",
            f"# Source: {self._cls.__name__}",
            "from __future__ import annotations",
            "import ctypes",
            "from typing import Callable, Optional",
            "",
        ]

    # ------------------------------------------------------------------
    # Class body
    # ------------------------------------------------------------------

    def _emit_class_body(self) -> List[str]:
        lines  = [f"class {self._class_name}:"]
        lines += self._emit_class_docstring()
        lines += self._emit_offset_consts()
        lines += self._emit_init_method()
        lines += self._emit_mmio_helpers()
        lines += self._emit_register_methods()
        return lines

    def _emit_class_docstring(self) -> List[str]:
        return [
            f'    """Hardware driver for {self._cls.__name__} register file.',
            "",
            "    Targets a real MMIO bus driver. Field access mirrors the",
            "    zdc simulation API.",
            '    """',
            "",
        ]

    def _emit_offset_consts(self) -> List[str]:
        lines = ["    # Register offsets"]
        for reg_name, reg_cls in self._regs:
            off = reg_cls._mmr_offset
            lines.append(f"    {reg_name.upper()}_OFFSET = 0x{off:02X}")
        lines.append("")
        return lines

    def _emit_init_method(self) -> List[str]:
        return [
            "    def __init__(",
            "        self,",
            "        base_addr: int,",
            "        read_fn:  Optional[Callable[[int], int]]      = None,",
            "        write_fn: Optional[Callable[[int, int], None]] = None,",
            "    ):",
            '        """',
            "        Args:",
            "            base_addr: Base address of the register file.",
            "            read_fn:   ``Callable(addr) -> int``. Default: raw MMIO.",
            "            write_fn:  ``Callable(addr, value)``. Default: raw MMIO.",
            '        """',
            "        self._base  = base_addr",
            "        self._read  = read_fn  or self._mmio_read",
            "        self._write = write_fn or self._mmio_write",
            "",
        ]

    def _emit_mmio_helpers(self) -> List[str]:
        return [
            "    # ------------------------------------------------------------------",
            "    # Low-level helpers",
            "    # ------------------------------------------------------------------",
            "",
            "    def _mmio_read(self, addr: int) -> int:",
            "        return ctypes.c_uint32.from_address(addr).value",
            "",
            "    def _mmio_write(self, addr: int, value: int) -> None:",
            "        ctypes.c_uint32.from_address(addr).value = value & 0xFFFF_FFFF",
            "",
            "    def _rd(self, offset: int) -> int:",
            "        return int(self._read(self._base + offset)) & 0xFFFF_FFFF",
            "",
            "    def _wr(self, offset: int, value: int) -> None:",
            "        self._write(self._base + offset, int(value) & 0xFFFF_FFFF)",
            "",
            "    def _rmw(self, offset: int, shift: int, mask: int, value: int) -> None:",
            "        old = self._rd(offset)",
            "        self._wr(offset, (old & ~mask) | ((value << shift) & mask))",
            "",
        ]

    # ------------------------------------------------------------------
    # Per-register and per-field methods
    # ------------------------------------------------------------------

    def _emit_register_methods(self) -> List[str]:
        from zuspec.dataclasses.mmr.enums import SW
        lines = [
            "    # ------------------------------------------------------------------",
            "    # Register and field accessors",
            "    # ------------------------------------------------------------------",
            "",
        ]
        for reg_name, reg_cls in self._regs:
            off     = reg_cls._mmr_offset
            rn_up   = reg_name.upper()
            fields  = getattr(reg_cls, '_mmr_fields', [])

            # raw register read
            lines += [
                f"    def read_{reg_name}(self) -> int:",
                f'        """Read raw value of the {reg_name} register."""',
                f"        return self._rd(0x{off:02X})",
                "",
            ]

            # raw register write
            lines += [
                f"    def write_{reg_name}(self, value: int) -> None:",
                f'        """Write raw value to the {reg_name} register."""',
                f"        self._wr(0x{off:02X}, value)",
                "",
            ]

            for fname, fd in fields:
                lsb  = fd.lsb
                w    = fd._width
                mask = (1 << w) - 1
                sw   = fd.sw

                # get method (SW-readable)
                if sw not in (SW.WO, SW.NA):
                    access_note = self._sw_str(sw)
                    lines += [
                        f"    def get_{reg_name}_{fname}(self) -> int:",
                        f'        """Read {reg_name}.{fname} field ({access_note}, bits [{lsb + w - 1}:{lsb}])."""',
                        f"        return (self._rd(0x{off:02X}) >> {lsb}) & 0x{mask:X}",
                        "",
                    ]

                # write / clear methods (SW-writable)
                if sw not in (SW.RO, SW.NA):
                    if getattr(fd, 'onwrite', None) == 'woclr':
                        lines += [
                            f"    def clr_{reg_name}_{fname}(self) -> None:",
                            f'        """Write-1-to-clear {reg_name}.{fname} (woclr)."""',
                            f"        self._wr(0x{off:02X}, 0x{mask:X} << {lsb})",
                            "",
                        ]
                    else:
                        lines += [
                            f"    def set_{reg_name}_{fname}(self, value: int) -> None:",
                            f'        """Write {reg_name}.{fname} field (read-modify-write)."""',
                            f"        self._rmw(0x{off:02X}, {lsb}, 0x{mask:X} << {lsb}, value)",
                            "",
                        ]

        return lines

    @staticmethod
    def _sw_str(sw) -> str:
        from zuspec.dataclasses.mmr.enums import SW
        return {
            SW.RW: "sw=rw",
            SW.RO: "sw=ro",
            SW.WO: "sw=wo",
            SW.NA: "sw=na",
        }.get(sw, str(sw))


# ---------------------------------------------------------------------------
# Standalone entry point
# ---------------------------------------------------------------------------

def emit_py_driver(regfile_cls, class_name: Optional[str] = None) -> str:
    """Generate a Python driver class for a ``RegisterFile`` subclass.

    Parameters
    ----------
    regfile_cls:
        A ``@zdc.regfile``-decorated ``RegisterFile`` subclass.
    class_name:
        Name for the generated class (default: ``<ClassName>Driver``).

    Returns
    -------
    str
        The complete Python driver source.
    """
    return MmrRegFilePyDriverEmitter(regfile_cls, class_name=class_name).emit()
